<a href="https://colab.research.google.com/github/officialaryansingh/machine_learning/blob/main/Handling_impbalanced_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Imbalanced Dataset**

A  dataset with an unequal class distribution

In [2]:
# importing the dependencies
import numpy as np
import pandas as pd

In [3]:
# laoding datasest to pandas dataFrame
credit_card_data = pd.read_csv('/content/credit_data.csv')

In [4]:
# First 5 rows of the dataFrame
print(credit_card_data.head())

   Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010

        V26       V27       V28  Amount  Class
0 -0.189115  0.133558 -0.021053  149.62      0
1  0.125895 -0.008983  0.014724    2.69      0
2 -0.139097 -0.055353 -0.059752  378.66      0
3 -0.221929  0.062723  0.061458  123.50      0
4  0.502292  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [5]:
#distribution of the two classes
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This is Highly Imbalaced Dataset

0--> Legit Transactions

1--> Fraudulent Transactions

In [6]:
# seperating the legit and fraudulent transactions
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [7]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

**Under-saampling**

Build a sample dataset containing similar distribution of legit & fraudulent Transactions

Number of fraudulent transactions --> 492

In [8]:
legit_sample = legit.sample(n=492)

In [9]:
print(legit_sample.shape)

(492, 31)

Concatenate the Two DataFrame

In [10]:
new_dataset = pd.concat([legit_sample,fraud],axis = 0)

In [11]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
53789,46148.0,-0.401224,-0.748595,1.881898,-1.021957,-1.552423,0.458845,-0.279814,0.393357,-0.352472,...,0.158845,0.196852,0.179992,-0.050172,-0.059220,-0.277547,0.010412,0.022004,147.54,0
241400,151010.0,1.575503,-0.879237,-1.971750,-0.074595,0.339711,-0.243331,0.488981,-0.246754,0.393033,...,0.444736,0.868548,-0.283773,0.291338,0.306457,-0.403616,-0.048474,-0.017685,259.00,0
98842,66843.0,1.427872,-0.820894,0.269327,-1.136990,-0.655599,0.580683,-1.172068,0.210650,-0.486429,...,0.323286,0.814981,-0.335333,-1.352359,0.610927,0.039817,0.026628,-0.000256,24.99,0
171122,120508.0,-0.215698,1.026149,2.250202,4.284006,-0.085403,3.872136,-2.356192,-1.604468,-1.571047,...,-1.030993,1.190467,-0.200785,-1.650563,0.712370,0.754482,0.157072,0.186002,1.00,0
602,455.0,1.179162,0.205327,0.704971,0.697812,-0.566141,-0.830944,-0.013824,-0.093148,0.026189,...,-0.196312,-0.543615,0.233359,0.597346,0.068706,0.091725,-0.012834,0.020738,1.98,0

In [12]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [13]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64