<a href="https://colab.research.google.com/github/officialaryansingh/machine_learning/blob/main/ML%20projects/Project_10_Credit_card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
# impoting the important dependencies
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [67]:
# loading the dataset to pandas DataFrame
credit_card_data = pd.read_csv('/content/credit_data.csv')

In [68]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [69]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [70]:
credit_card_data.shape

(284807, 31)

In [71]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [72]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [73]:
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This dataset is Highly unbalanced

0 --> Normal Transaction

1--> Fraud Transaction

In [74]:
# seperating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [75]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [76]:
# statistical information
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [77]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [78]:
# compare the values for both transaction
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Under Sampling

Build a sample dataset containing similar distribution of normal trancation and
fraudulent transaction

number of Fraudlent Transactions --> 470

In [79]:
legit_sample = legit.sample(n=470)

In [80]:
# concatenating two DataFrame
new_dataset = pd.concat([legit_sample,fraud],axis = 0)

In [81]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
25374,33579.0,1.186016,-0.496397,0.527477,-1.463137,-1.001318,-0.674709,-0.524294,0.148376,1.308845,...,-0.070701,-0.203166,0.131021,0.203439,0.087183,-0.146660,0.016179,0.009754,12.50,0
149426,91214.0,-2.652646,1.160807,-1.230251,0.292747,3.041598,-0.132048,3.091049,-2.478770,3.667809,...,-0.932328,0.857029,0.168530,-0.394693,-0.206350,-0.730548,-0.701517,-0.315075,25.00,0
9659,14452.0,1.220511,-0.217204,0.473477,-0.031218,-0.281988,0.425626,-0.726072,0.214482,1.733283,...,-0.059419,0.027329,-0.089054,-0.853363,0.174851,1.101075,-0.086621,-0.019293,15.95,0
273371,165570.0,2.063385,0.104122,-1.899299,0.634898,0.417652,-0.715733,0.018136,-0.169347,0.851639,...,-0.055652,0.122815,0.053047,0.502111,0.132763,0.616141,-0.046229,-0.026135,1.00,0
15415,26799.0,1.144915,-1.576920,1.028820,-1.176689,-2.066807,-0.347007,-1.265969,-0.023116,-1.593941,...,-0.002692,0.130921,0.026728,0.394081,0.020001,-0.227099,0.058215,0.059420,152.65,0

In [82]:
new_dataset['Class'].value_counts()

Class
1    492
0    470
Name: count, dtype: int64

In [83]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94906.972340,0.081121,-0.020944,-0.031268,-0.106998,0.089880,-0.043587,-0.038300,-0.017845,0.001236,...,-0.010689,-0.019761,0.040215,0.012953,-0.00671,0.015184,-0.015172,0.008075,-0.012307,72.967085
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.10513,0.041449,0.051648,0.170575,0.075667,122.211321

Splitting the data into Features & Targets

In [84]:
X = new_dataset.drop(columns = 'Class',axis = 1)
Y = new_dataset['Class']

In [85]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
25374    33579.0  1.186016 -0.496397  0.527477 -1.463137 -1.001318 -0.674709
149426   91214.0 -2.652646  1.160807 -1.230251  0.292747  3.041598 -0.132048
9659     14452.0  1.220511 -0.217204  0.473477 -0.031218 -0.281988  0.425626
273371  165570.0  2.063385  0.104122 -1.899299  0.634898  0.417652 -0.715733
15415    26799.0  1.144915 -1.576920  1.028820 -1.176689 -2.066807 -0.347007
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
25374  -0.524294  0.148376  1.308845  ... -0.173520 -0.070701 -0.203166
149426  3.091049 -2.478770  3.667809  ...  0.477619 -0.932328  0.857029
9659   -0.726072  0.214482  1.733283  ... -0.158324 -0.059419  0.027329
273371  0.018136 -0.169347  0.851639  ... -0.164681 -0.055652  0.122815
15415  -1.265969 -0.023116 -1.593941  ... -0.037484 -0.002692  0.130921
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
25374   0.131021  0.203439  0.087183 -0.146660  0.016179  0.009754   12.50
149426  0.168530 -0.394693 -0.206350 -0.730548 -0.701517 -0.315075   25.00
9659   -0.089054 -0.853363  0.174851  1.101075 -0.086621 -0.019293   15.95
273371  0.053047  0.502111  0.132763  0.616141 -0.046229 -0.026135    1.00
15415   0.026728  0.394081  0.020001 -0.227099  0.058215  0.059420  152.65
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[962 rows x 30 columns]

In [86]:
print(Y)

25374     0
149426    0
9659      0
273371    0
15415     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 962, dtype: int64

Splitting the data in Training data and Testing Data

In [87]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,stratify = Y,random_state = 2)

In [88]:
print(X.shape,X_train.shape,X_test.shape)

(962, 30) (769, 30) (193, 30)

Model Training

Logistic Regression

In [89]:
model = LogisticRegression()

In [90]:
model.fit(X_train,Y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evalution

Accuracy Score

In [91]:
# accuracy on trainig data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [92]:
print('Accuracy on training on Training data : ', training_data_accuracy)

Accuracy on training on Training data :  0.9427828348504551

In [93]:
# accuracy for testing data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

In [94]:
print('Accuracy score on test data : ',test_data_accuracy)

Accuracy score on test data :  0.9326424870466321

Building a predictive system

In [96]:
user_input = input("Enter the here (comma seperated) : ")

# converting the input into the list of floats (or ints)
input_data = [float(x) for x in user_input.split(',')]

# change the data into the numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshaping the numpy array as  we are only prediticting on instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if(prediction == 0):
  print("The transaction is legit")

else:
  print("The transaction is fraud")

Enter the here (comma seperated) : 1,-0.966271711572087,-0.185226008082898,1.79299333957872,-0.863291275036453,-0.0103088796030823,1.24720316752486,0.23760893977178,0.377435874652262,-1.38702406270197,-0.0549519224713749,-0.226487263835401,0.178228225877303,0.507756869957169,-0.28792374549456,-0.631418117709045,-1.0596472454325,-0.684092786345479,1.96577500349538,-1.2326219700892,-0.208037781160366,-0.108300452035545,0.00527359678253453,-0.190320518742841,-1.17557533186321,0.647376034602038,-0.221928844458407,0.0627228487293033,0.0614576285006353,123.5
[0]
The transaction is legit

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(