<a href="https://colab.research.google.com/github/officialaryansingh/machine_learning/blob/main/ML%20projects/Project_10_Credit_card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# impoting the important dependencies
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
# loading the dataset to pandas DataFrame
credit_card_data = pd.read_csv('/content/credit_data.csv')

In [3]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [4]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
13949,24754,1.252924,-0.182189,-0.802716,-0.210981,1.916713,3.643624,-0.778711,0.818295,1.706962,...,-0.497088,-1.211285,0.043809,0.964159,0.442030,0.261483,-0.051402,0.005112,23.74,0.0
13950,24756,-0.346979,-2.103284,-0.685061,1.961605,-0.401125,0.473632,1.133816,-0.256528,0.893409,...,0.359662,-0.316275,-0.864259,-0.279881,0.491802,-0.353996,-0.149931,0.129795,794.20,0.0
13951,24759,-6.053652,-5.988723,0.810413,-0.011811,1.308135,-0.590803,-0.725838,-0.234840,1.624646,...,-0.771970,1.474668,3.176363,-0.302410,0.052529,-0.373871,-0.700463,2.508443,60.00,0.0
13952,24759,1.169121,-1.284945,0.032717,-0.681670,0.660598,4.412578,-1.913115,1.076592,1.501230,...,-0.557596,-0.882435,-0.041523,0.975445,0.297229,0.550515,0.015029,0.032067,90.00,0.0
13953,24759,-6.917152,5.854171,-1.652458,-1.488884,-0.833891,-0.344418,0.393789,0.379968,6.133597,...,-1.404681,-1.124694,0.174333,-0.528234,0.990685,-0.035875,1.071374,-0.168831,NaN,NaN

In [5]:
credit_card_data.shape

(13954, 31)

In [6]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13954 entries, 0 to 13953
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    13954 non-null  int64
 1   V1      13954 non-null  float64
 2   V2      13954 non-null  float64
 3   V3      13954 non-null  float64
 4   V4      13954 non-null  float64
 5   V5      13954 non-null  float64
 6   V6      13954 non-null  float64
 7   V7      13954 non-null  float64
 8   V8      13954 non-null  float64
 9   V9      13954 non-null  float64
 10  V10     13954 non-null  float64
 11  V11     13954 non-null  float64
 12  V12     13954 non-null  float64
 13  V13     13954 non-null  float64
 14  V14     13954 non-null  float64
 15  V15     13954 non-null  float64
 16  V16     13954 non-null  float64
 17  V17     13954 non-null  float64
 18  V18     13954 non-null  float64
 19  V19     13954 non-null  float64
 20  V20     13954 non-null  float64
 21  V21     13954 non-null  float64
 22  V22     13954 non-null  float64
 23  V23     13954 non-null  float64
 24  V24     13954 non-null  float64
 25  V25     13954 non-null  float64
 26  V26     13954 non-null  float64
 27  V27     13954 non-null  float64
 28  V28     13954 non-null  float64
 29  Amount  13953 non-null  float64
 30  Class   13953 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 3.3 MB

In [7]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    1
Class     1
dtype: int64

In [8]:
credit_card_data['Class'].value_counts()

Class
0.0    13897
1.0       56
Name: count, dtype: int64

This dataset is Highly unbalanced

0 --> Normal Transaction

1--> Fraud Transaction

In [9]:
# seperating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [10]:
print(legit.shape)
print(fraud.shape)

(13897, 31)
(56, 31)

In [11]:
# statistical information
legit.Amount.describe()

count    13897.000000
mean        63.773909
std        177.164503
min          0.000000
25%          5.770000
50%         15.900000
75%         52.370000
max       7712.430000
Name: Amount, dtype: float64

In [12]:
fraud.Amount.describe()

count      56.000000
mean       90.815893
std       310.308450
min         0.000000
25%         1.000000
50%         1.000000
75%         1.025000
max      1809.680000
Name: Amount, dtype: float64

In [13]:
# compare the values for both transaction
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,10111.481255,-0.217093,0.266252,0.887227,0.276789,-0.107510,0.136745,-0.131462,-0.020385,1.005460,...,0.020758,-0.068686,-0.158230,-0.034834,0.013065,0.117928,0.034349,0.009565,0.002329,63.773909
1.0,12262.107143,-4.727948,4.660436,-9.328536,6.783464,-2.890388,-2.030360,-6.578337,1.028374,-2.981468,...,0.453283,0.116896,0.048132,-0.225526,-0.452514,-0.124184,0.333325,0.793484,-0.046177,90.815893

Under Sampling

Build a sample dataset containing similar distribution of normal trancation and
fraudulent transaction

number of Fraudlent Transactions --> 470

In [14]:
legit_sample = legit.sample(n=470)

In [15]:
# concatenating two DataFrame
new_dataset = pd.concat([legit_sample,fraud],axis = 0)

In [16]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
10802,18401,-0.701291,0.867343,1.227909,0.519263,0.545996,-0.589155,0.136631,0.018104,0.809691,...,-0.337653,-0.696294,-0.022397,-0.109708,-0.729789,0.063311,0.258335,0.197124,4.48,0.0
12315,21554,1.282280,0.707469,0.056567,1.298413,0.223180,-1.117798,0.543651,-0.507445,0.816060,...,-0.133501,-0.016287,-0.147869,0.379836,0.872219,-0.339194,-0.026319,0.007125,0.89,0.0
8092,11017,1.302043,-0.261503,-0.722756,-0.853728,1.700463,3.426329,-1.013726,0.793970,1.596136,...,-0.119160,-0.231570,-0.051550,1.022013,0.368303,1.046159,-0.086748,-0.000809,15.95,0.0
11884,20456,-2.322010,-2.691396,0.754978,0.021225,-1.669255,0.253903,2.046121,-0.230177,-0.538370,...,0.063118,-0.766524,1.804665,-0.065243,0.324217,1.144459,-0.325676,0.121355,769.66,0.0
9336,13536,-0.619359,1.400167,1.041291,-0.127694,0.827773,-1.164008,1.036133,-0.229195,0.160604,...,-0.118866,-0.136960,-0.263625,0.398748,0.087844,0.133134,0.014175,0.117147,0.76,0.0

In [17]:
new_dataset['Class'].value_counts()

Class
0.0    470
1.0     56
Name: count, dtype: int64

In [18]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,10889.540426,-0.176515,0.269598,0.746121,0.366617,-0.190719,0.119265,-0.140194,0.046150,1.077642,...,-0.003639,-0.111982,-0.218273,-0.030981,0.012124,0.127379,0.028122,-0.033040,-0.013202,68.027298
1.0,12262.107143,-4.727948,4.660436,-9.328536,6.783464,-2.890388,-2.030360,-6.578337,1.028374,-2.981468,...,0.453283,0.116896,0.048132,-0.225526,-0.452514,-0.124184,0.333325,0.793484,-0.046177,90.815893

Splitting the data into Features & Targets

In [19]:
X = new_dataset.drop(columns = 'Class',axis = 1)
Y = new_dataset['Class']

In [20]:
print(X)

        Time         V1         V2         V3         V4         V5        V6  \
10802  18401  -0.701291   0.867343   1.227909   0.519263   0.545996 -0.589155
12315  21554   1.282280   0.707469   0.056567   1.298413   0.223180 -1.117798
8092   11017   1.302043  -0.261503  -0.722756  -0.853728   1.700463  3.426329
11884  20456  -2.322010  -2.691396   0.754978   0.021225  -1.669255  0.253903
9336   13536  -0.619359   1.400167   1.041291  -0.127694   0.827773 -1.164008
...      ...        ...        ...        ...        ...        ...       ...
11880  20451 -15.819179   8.775997 -22.804686  11.864868  -9.092361 -2.386893
12070  20931 -16.367923   9.223692 -23.270631  11.844777  -9.462037 -2.450444
12108  21046 -16.917468   9.669900 -23.736443  11.824990  -9.830548 -2.514829
12261  21419 -17.467710  10.114816 -24.202142  11.805469 -10.198046 -2.579938
12369  21662 -18.018561  10.558600 -24.667741  11.786180 -10.564657 -2.645681

              V7        V8        V9  ...       V20       V21       V22  \
10802   0.136631  0.018104  0.809691  ...  0.048054 -0.337653 -0.696294
12315   0.543651 -0.507445  0.816060  ... -0.119456 -0.133501 -0.016287
8092   -1.013726  0.793970  1.596136  ...  0.046663 -0.119160 -0.231570
11884   2.046121 -0.230177 -0.538370  ...  1.483496  0.063118 -0.766524
9336    1.036133 -0.229195  0.160604  ... -0.069777 -0.118866 -0.136960
...          ...       ...       ...  ...       ...       ...       ...
11880 -16.560368  0.948349 -6.310658  ...  0.992279 -2.350634  1.036362
12070 -16.925152  1.384208 -6.287736  ...  0.993585 -2.343674  1.004602
12108 -17.290657  1.820408 -6.264903  ...  0.996745 -2.336111  0.972755
12261 -17.656788  2.256902 -6.242149  ...  1.001519 -2.328024  0.940830
12369 -18.023468  2.693655 -6.219464  ...  1.007703 -2.319479  0.908839

            V23       V24       V25       V26       V27       V28  Amount
10802 -0.022397 -0.109708 -0.729789  0.063311  0.258335  0.197124    4.48
12315 -0.147869  0.379836  0.872219 -0.339194 -0.026319  0.007125    0.89
8092  -0.051550  1.022013  0.368303  1.046159 -0.086748 -0.000809   15.95
11884  1.804665 -0.065243  0.324217  1.144459 -0.325676  0.121355  769.66
9336  -0.263625  0.398748  0.087844  0.133134  0.014175  0.117147    0.76
...         ...       ...       ...       ...       ...       ...     ...
11880  1.136051 -1.043414 -0.108923  0.657437  2.136424 -1.411945    1.00
12070  1.188212 -1.047184 -0.035573  0.664900  2.122796 -1.416741    1.00
12108  1.241866 -1.051086  0.038009  0.672317  2.108471 -1.421243    1.00
12261  1.296817 -1.055104  0.111792  0.679695  2.093541 -1.425491    1.00
12369  1.352904 -1.059222  0.185751  0.687037  2.078081 -1.429517    1.00

[526 rows x 30 columns]

In [21]:
print(Y)

10802    0.0
12315    0.0
8092     0.0
11884    0.0
9336     0.0
        ...
11880    1.0
12070    1.0
12108    1.0
12261    1.0
12369    1.0
Name: Class, Length: 526, dtype: float64

Splitting the data in Training data and Testing Data

In [22]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,stratify = Y,random_state = 2)

In [23]:
print(X.shape,X_train.shape,X_test.shape)

(526, 30) (420, 30) (106, 30)

Model Training

Logistic Regression

In [24]:
model = LogisticRegression()

In [25]:
model.fit(X_train,Y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evalution

Accuracy Score

In [26]:
# accuracy on trainig data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [27]:
print('Accuracy on training on Training data : ', training_data_accuracy)

Accuracy on training on Training data :  0.9928571428571429

In [28]:
# accuracy for testing data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

In [29]:
print('Accuracy score on test data : ',test_data_accuracy)

Accuracy score on test data :  0.9716981132075472

Building a predictive system

In [30]:
user_input = input("Enter the here (comma seperated) : ")

# converting the input into the list of floats (or ints)
input_data = [float(x) for x in user_input.split(',')]

# change the data into the numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshaping the numpy array as  we are only prediticting on instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if(prediction == 0):
  print("The transaction is legit")

else:
  print("The transaction is fraud")

Enter the here (comma seperated) : 1,-0.966271711572087,-0.185226008082898,1.79299333957872,-0.863291275036453,-0.0103088796030823,1.24720316752486,0.23760893977178,0.377435874652262,-1.38702406270197,-0.0549519224713749,-0.226487263835401,0.178228225877303,0.507756869957169,-0.28792374549456,-0.631418117709045,-1.0596472454325,-0.684092786345479,1.96577500349538,-1.2326219700892,-0.208037781160366,-0.108300452035545,0.00527359678253453,-0.190320518742841,-1.17557533186321,0.647376034602038,-0.221928844458407,0.0627228487293033,0.0614576285006353,123.5
[0.]
The transaction is legit

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [31]:
print("Thank you for using this prediction model! (-_-)")

Thank you for using this prediction model! (-_-)