<a href="https://colab.research.google.com/github/officialaryansingh/machine_learning/blob/main/ML%20projects/Project_10_Credit_card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# impoting the important dependencies
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [5]:
# loading the dataset to pandas DataFrame
credit_card_data = pd.read_csv('/content/credit_data.csv')

In [6]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [8]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
257452,158172.0,-1.120369,0.501011,-1.529317,0.695992,2.181396,-0.997850,1.100139,-0.126678,-0.323019,...,-0.141843,0.281271,0.571184,0.138720,0.539882,-0.568312,-0.275066,-0.413842,1.00,0.0
257453,158174.0,-0.156508,0.656963,-0.135510,-0.120234,-0.110735,0.026058,0.146752,0.530776,0.563762,...,-0.266351,-0.710929,0.521638,0.568582,-1.221039,-0.072223,-0.000540,0.088254,72.90,0.0
257454,158175.0,2.063160,0.057377,-1.226656,0.351724,0.050100,-1.223581,0.268653,-0.427801,0.462757,...,0.278107,1.036505,-0.006535,0.056109,0.277374,-0.102485,-0.005481,-0.055708,1.00,0.0
257455,158176.0,-1.266069,1.182223,-0.639260,0.979701,0.210889,-0.251421,0.337728,0.770269,-1.263478,...,0.298574,0.515923,-0.531365,0.736880,0.896669,0.447270,-0.330024,-0.142205,37.97,0.0
257456,158176.0,-0.873452,0.602545,-0.160409,-0.477630,0.316238,-1.148471,0.905051,-0.015166,0.081742,...,-0.275979,-0.565464,0.090000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
credit_card_data.shape

(257457, 31)

In [10]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257457 entries, 0 to 257456
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    257457 non-null  float64
 1   V1      257457 non-null  float64
 2   V2      257457 non-null  float64
 3   V3      257457 non-null  float64
 4   V4      257457 non-null  float64
 5   V5      257457 non-null  float64
 6   V6      257457 non-null  float64
 7   V7      257457 non-null  float64
 8   V8      257457 non-null  float64
 9   V9      257457 non-null  float64
 10  V10     257457 non-null  float64
 11  V11     257457 non-null  float64
 12  V12     257457 non-null  float64
 13  V13     257457 non-null  float64
 14  V14     257457 non-null  float64
 15  V15     257457 non-null  float64
 16  V16     257457 non-null  float64
 17  V17     257457 non-null  float64
 18  V18     257457 non-null  float64
 19  V19     257457 non-null  float64
 20  V20     257457 non-null  float64
 21  V21     257457 non-null  float64
 22  V22     257457 non-null  float64
 23  V23     257457 non-null  float64
 24  V24     257456 non-null  float64
 25  V25     257456 non-null  float64
 26  V26     257456 non-null  float64
 27  V27     257456 non-null  float64
 28  V28     257456 non-null  float64
 29  Amount  257456 non-null  float64
 30  Class   257456 non-null  float64
dtypes: float64(31)
memory usage: 60.9 MB

In [11]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [12]:
credit_card_data['Class'].value_counts()

Class
0.0    256986
1.0       470
Name: count, dtype: int64

This dataset is Highly unbalanced

0 --> Normal Transaction

1--> Fraud Transaction

In [13]:
# seperating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [19]:
print(legit.shape)
print(fraud.shape)

(256986, 31)
(470, 31)

In [16]:
# statistical information
legit.Amount.describe()

count    256986.000000
mean         90.251211
std         250.331175
min           0.000000
25%           5.990000
50%          22.950000
75%          79.070000
max       19656.530000
Name: Amount, dtype: float64

In [17]:
fraud.Amount.describe()

count     470.000000
mean      122.636404
std       260.193766
min         0.000000
25%         1.000000
50%         8.770000
75%       104.615000
max      2125.870000
Name: Amount, dtype: float64

In [18]:
# compare the values for both transaction
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,87403.372666,-0.016966,-0.024598,0.090264,0.009930,-0.024115,0.016705,-0.002299,0.000402,0.005217,...,0.002960,-0.002402,-0.007955,-0.004477,0.001341,0.016002,0.001056,-0.000933,0.000536,90.251211
1.0,76838.787234,-4.916086,3.753249,-7.167910,4.618699,-3.319744,-1.384064,-5.737824,0.615789,-2.626903,...,0.368304,0.742969,0.002737,-0.052985,-0.105980,0.046062,0.048818,0.162808,0.075408,122.636404

Under Sampling

Build a sample dataset containing similar distribution of normal trancation and
fraudulent transaction

number of Fraudlent Transactions --> 470

In [20]:
legit_sample = legit.sample(n=470)

In [22]:
# concatenating two DataFrame
new_dataset = pd.concat([legit_sample,fraud],axis = 0)

In [24]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
127527,78363.0,1.277155,0.163061,0.183682,0.312494,-0.040188,-0.201073,-0.076131,0.008282,-0.121612,...,-0.263392,-0.803325,0.025519,-0.508834,0.289892,0.129299,-0.035354,-0.000214,0.89,0.0
105883,69732.0,-0.551026,0.125879,2.672509,0.034917,0.335036,2.182984,-0.284970,0.431064,0.197368,...,0.414878,1.657157,-0.104362,-0.973429,-0.977970,0.540192,-0.232610,-0.311198,16.57,0.0
234420,147966.0,0.021941,1.018144,-0.648685,-0.799657,1.209104,-0.210236,0.831649,0.047102,-0.169412,...,-0.310851,-0.839433,0.030978,-0.019216,-0.396176,0.116410,0.080303,0.065991,1.29,0.0
123825,77080.0,1.404242,-1.325666,1.355792,-1.278575,-2.253269,-0.452351,-1.666845,-0.009475,-1.297096,...,0.096711,0.666130,-0.032357,0.406679,0.208944,-0.045741,0.080921,0.044336,42.50,0.0
14869,26148.0,0.885470,-0.921396,0.728598,0.216118,-0.911311,0.427335,-0.502693,0.164703,1.175238,...,-0.136056,-0.453361,-0.100572,-0.336054,0.078555,0.984908,-0.047106,0.035069,173.09,0.0

In [25]:
new_dataset['Class'].value_counts()

Class
0.0    470
1.0    470
Name: count, dtype: int64

In [26]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,89321.400000,0.072689,-0.120567,0.13317,-0.097022,-0.002326,0.021060,-0.064377,0.047822,-0.008910,...,0.025563,0.022131,-0.015029,-0.015908,-0.00606,-0.036521,0.016047,0.017629,0.004681,93.773894
1.0,76838.787234,-4.916086,3.753249,-7.16791,4.618699,-3.319744,-1.384064,-5.737824,0.615789,-2.626903,...,0.368304,0.742969,0.002737,-0.052985,-0.10598,0.046062,0.048818,0.162808,0.075408,122.636404

Splitting the data into Features & Targets

In [27]:
X = new_dataset.drop(columns = 'Class',axis = 1)
Y = new_dataset['Class']

In [28]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
127527   78363.0  1.277155  0.163061  0.183682  0.312494 -0.040188 -0.201073
105883   69732.0 -0.551026  0.125879  2.672509  0.034917  0.335036  2.182984
234420  147966.0  0.021941  1.018144 -0.648685 -0.799657  1.209104 -0.210236
123825   77080.0  1.404242 -1.325666  1.355792 -1.278575 -2.253269 -0.452351
14869    26148.0  0.885470 -0.921396  0.728598  0.216118 -0.911311  0.427335
...          ...       ...       ...       ...       ...       ...       ...
252774  155965.0 -1.201398  4.864535 -8.328823  7.652399 -0.167445 -2.767695
254344  156685.0 -0.129778  0.141547 -0.894702 -0.457662  0.810608 -0.504723
254395  156710.0  0.202402  1.176270  0.346379  2.882138  1.407133 -0.504355
255403  157207.0  1.170756  2.501038 -4.986159  5.374160  0.997798 -1.259004
255556  157284.0 -0.242245  4.147186 -5.672349  6.493741  1.591168 -1.602523

              V7        V8        V9  ...       V20       V21       V22  \
127527 -0.076131  0.008282 -0.121612  ... -0.072587 -0.263392 -0.803325
105883 -0.284970  0.431064  0.197368  ...  0.049727  0.414878  1.657157
234420  0.831649  0.047102 -0.169412  ...  0.016550 -0.310851 -0.839433
123825 -1.666845 -0.009475 -1.297096  ... -0.214055  0.096711  0.666130
14869  -0.502693  0.164703  1.175238  ...  0.258917 -0.136056 -0.453361
...          ...       ...       ...  ...       ...       ...       ...
252774 -3.176421  1.623279 -4.367228  ...  0.597026  0.532320 -0.556913
254344  1.373588 -0.209476  0.208494  ...  0.399447 -0.032643 -0.246526
254395  1.438537 -0.395603 -1.555142  ... -0.206239  0.242560  0.841230
255403 -1.237689  0.358426 -2.612489  ...  0.227618  0.123145 -0.713201
255556 -0.950463  0.722903 -4.128505  ...  0.562030  0.249023 -0.480286

             V23       V24       V25       V26       V27       V28  Amount
127527  0.025519 -0.508834  0.289892  0.129299 -0.035354 -0.000214    0.89
105883 -0.104362 -0.973429 -0.977970  0.540192 -0.232610 -0.311198   16.57
234420  0.030978 -0.019216 -0.396176  0.116410  0.080303  0.065991    1.29
123825 -0.032357  0.406679  0.208944 -0.045741  0.080921  0.044336   42.50
14869  -0.100572 -0.336054  0.078555  0.984908 -0.047106  0.035069  173.09
...          ...       ...       ...       ...       ...       ...     ...
252774  0.192444 -0.698588  0.025003  0.514968  0.378105 -0.053133    0.77
254344  0.484108  0.359637 -0.435972 -0.248480  0.021527  0.109192  187.11
254395 -0.370157 -0.026012  0.491954  0.234576 -0.279788 -0.331933    7.59
255403 -0.080868 -0.964310  0.338568  0.068630  0.481588  0.268226    4.97
255556 -0.286080 -1.153575 -0.035571  0.559628  0.409446  0.221048    0.77

[940 rows x 30 columns]

In [29]:
print(Y)

127527    0.0
105883    0.0
234420    0.0
123825    0.0
14869     0.0
         ...
252774    1.0
254344    1.0
254395    1.0
255403    1.0
255556    1.0
Name: Class, Length: 940, dtype: float64